# Generated by Django 2.2.6 on 2019-11-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20191127_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', max_length=150, upload_to='teacher/%Y/%m', verbose_name='教师封面'),
        ),
    ]
